Add optional max-depth feature
jacwah/ntree pull request #4
Opened 2018-05-31 02:03 UTC by joshlemer

Adds an option `-L` / `--level` which limits the depth to which oak will traverse the filesystem.

2018-06-02 10:51 UTC, jacwah commented
Thank, looks cool! I'll make sure to check it out properly within a few days.

2018-06-12 11:00 UTC, jacwah requested changes
It was a while since I worked on this project, it's fun to see that you're interested! I just had a small request regarding the help message, otherwise I'm all for merging this.

2018-06-12 11:00 UTC, jacwah commented on src/main.rs
> +            .help("Max display depth of directory tree.")
It would be nice if the help text better matches the other ones. Maybe something like "Limit max listing depth". You probably have a good suggestion.

2018-06-12 11:00 UTC, jacwah commented on src/tree.rs
> +        let entry = self.dir_stack.last_mut().map(next_entry);
I love this!

2018-06-12 11:00 UTC, jacwah commented on src/tree.rs
> +            Some(Some(Ok(e))) => e,
This is also good because it succinctly summarizes the different cases.

2018-06-12 20:40 UTC, joshlemer commented on src/main.rs
> +            .help("Max display depth of directory tree.")
Ah yes I see that my phrasing was more descriptive of what the property is, rather than a directive of what to use it for. Thanks!

2021-02-09 19:39 UTC, closed without merging